[package]
name = "facecam"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.36.2"
nokhwa = { version = "0.10.11", features = ["input-native"] }
nokhwa-core = "=0.1.9"
rand = "0.10.3"
virtualcam-rs = "0.1.0"
image = "0.25.10"
imageproc = "0.27.0"
ndarray = "0.17.2"
fast_image_resize = "6.1.0"
ort = "2.0.0-rc.13"
tokio = { version = "1.53.1", features = ["full"] }
